"""Export a small browser-safe strategy index from the repaired knowledge pack.

The calculator is a static local app, so it cannot query SQLite directly when
opened with file://. This exporter keeps the database authoritative and emits
only the compact mechanics, rules, provenance counts and coverage warnings the
Phase 2 Library needs. It never reads account data or uses the network.
"""
from __future__ import annotations

import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path

CALCULATOR = Path(__file__).resolve().parents[1]
DB_PATH = CALCULATOR.parent / "knowledge-pack" / "farmrpg.db"
OUTPUT = CALCULATOR / "data" / "knowledge.js"


def rows(db: sqlite3.Connection, sql: str):
    return [dict(row) for row in db.execute(sql)]


def main() -> None:
    if not DB_PATH.exists():
        raise SystemExit(f"Knowledge database not found: {DB_PATH}")
    db = sqlite3.connect(DB_PATH)
    db.row_factory = sqlite3.Row
    integrity = db.execute("PRAGMA integrity_check").fetchone()[0]
    if integrity != "ok":
        raise SystemExit(f"Knowledge database integrity failed: {integrity}")

    table_names = [
        "sources", "items", "recipes", "locations", "quests",
        "quest_requirements", "mastery_requirements", "perks", "meals",
        "trade_quotes", "user_rules", "conflicts", "unmatched_names",
        "evidence_sources",
    ]
    counts = {
        name: db.execute(f"SELECT COUNT(*) FROM {name}").fetchone()[0]
        for name in table_names
    }
    source_status = {
        row[0]: row[1]
        for row in db.execute("SELECT status, COUNT(*) FROM sources GROUP BY status")
    }

    payload = {
        "meta": {
            "generatedAt": datetime.now(timezone.utc).isoformat(),
            "databaseModifiedAt": datetime.fromtimestamp(
                DB_PATH.stat().st_mtime, timezone.utc
            ).isoformat(),
            "integrity": integrity,
            "counts": counts,
            "sourceStatus": source_status,
            "warning": (
                "Coverage is incomplete. Captured-but-unparsed sources, thin quest "
                "rewards and missing structured infrastructure remain visible gaps."
            ),
        },
        "rules": rows(
            db,
            "SELECT rule, topic, needs_verification AS needsVerification, "
            "confirmed_by AS confirmedBy, source_id AS source "
            "FROM user_rules ORDER BY topic, rule",
        ),
        "meals": rows(
            db,
            "SELECT canonical_name AS name, duration, action_charges AS actionCharges, "
            "effect_text AS effect, source_id AS source FROM meals ORDER BY canonical_name",
        ),
        "perks": rows(
            db,
            "SELECT canonical_name AS name, category, effect_text AS effect, "
            "effect_type AS effectType, numeric_effect AS numericEffect, "
            "source_id AS source FROM perks ORDER BY category, canonical_name",
        ),
        "conflicts": rows(
            db,
            "SELECT subject, field, value_a AS valueA, source_a AS sourceA, "
            "value_b AS valueB, source_b AS sourceB, status FROM conflicts ORDER BY subject",
        ),
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    encoded = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    OUTPUT.write_text(
        "/* Generated by tools/export-knowledge.py. Do not hand-edit. */\n"
        f"window.FRPG_KNOWLEDGE={encoded};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT} ({OUTPUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
